-- =====================================================================================
-- 🚨 MIGRATION STATUS: PENDING
-- Date Created: June 10, 2025
-- Purpose: Remove unique constraint from form_number in form_instances
-- Rationale: Form numbers are user-editable and should not be globally unique. This allows users to set any form number, including duplicates, as required by business logic.
-- =====================================================================================

-- Drop the unique constraint on form_number
ALTER TABLE form_instances DROP CONSTRAINT IF EXISTS form_instances_form_number_key;

-- Note: The form_number will remain NOT NULL and auto-generated by trigger if not provided. 